#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${POSTGRES_USER_2} WITH PASSWORD '${POSTGRES_PASSWORD_2}';
    CREATE DATABASE ${POSTGRES_DB_2};
    GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_DB_2} TO ${POSTGRES_USER_2};
EOSQL
